services:
  strapi:
    image: wodby/node:${NODE_TAG}
    container_name: ${PROJECT_NAME}_strapi
    working_dir: /usr/src/app
    environment:
      DATABASE_CLIENT: $DB_DRIVER
      DATABASE_NAME: $DB_NAME
      DATABASE_HOST: $DB_HOST
      DATABASE_PORT: 5432
      DATABASE_USERNAME: $DB_USER
      DATABASE_PASSWORD: $DB_PASSWORD
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./strapi:/usr/src/app
    command: >
      sh -c 'npm run local-develop'
    depends_on:
      - postgres
    ports:
      - 1337:1337

  app:
    image: wodby/node:${NODE_TAG}
    container_name: "${PROJECT_NAME}_app"
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    command: >
      sh -c 'npm run dev'
    ports:
      - 3000:3000

  postgres:
    image: gitlab-registry.studiopresent.com/k8s/registry/postgres-dev:${POSTGRES_TAG}
    container_name: "${PROJECT_NAME}_postgres"
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      DEV_POSTGRES_HOST: $DEV_DB_HOST
      DEV_POSTGRES_PORT: $DEV_DB_PORT

  adminer:
    image: wodby/adminer:$ADMINER_TAG
    container_name: "${PROJECT_NAME}_adminer"
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_HOST: $DB_HOST
      ADMINER_DEFAULT_DB_NAME: $DB_NAME
    depends_on:
      - postgres
    profiles: ["adminer"]
    ports:
      - 9000:9000

  mailhog:
    image: mailhog/mailhog:$MAILHOG_TAG
    container_name: "${PROJECT_NAME}_mailhog"
    ports:
      - 8025:8025

volumes:
  certs:
    driver: local
